### ISSUE TITLE
Update to the latest 3.x Opossum

### ISSUE THREAD

**Issue by lholmquist** [nodeshift-starters/opossum-examples#2]
and make sure all the examples work with the new version

**Comment by lance** [comment]
The new version now contains a fix that should ensure compatibility: https://github.com/nodeshift/opossum/pull/341

**Comment by helio-frota** [comment]
Probably better to wait for https://github.com/nodeshift/opossum/pull/350

**Comment by helio-frota** [comment]
jquery example updated https://github.com/nodeshift-starters/opossum-examples/pull/3

**Comment by helio-frota** [comment]
seneca example updated #4

**Comment by helio-frota** [comment]
react example fixed and working with opossum 3.0.0 #5

**Comment by helio-frota** [comment]
angular example fixed and working with opossum 3.0.0 #6

**Comment by helio-frota** [comment]
@lholmquist I think we can close it since we are going to deprecate hystrix.
Closing now we can reopen in case needed.
