### ISSUE TITLE
Update the mysql example to use podman instead of docker

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/opossum-examples#331]
https://github.com/nodeshift-starters/opossum-examples/blob/7e645cd1db1b7d5813a519e20a5b0f04475bb693/more-examples/database-timeout/README.md#basic-example-with-a-query-that-delays

**Comment by pacostas** [comment]
I would suggest replacing "docker" keyword with "docker | podman" keywords, instead of replacing "docker" keyword with "podman" keyword

**Comment by pacostas** [comment]
@helio-frota Yes! there is 100% feature parity between docker and podman.

**Comment by helio-frota** [comment]
@pacostas great! Can you please send a PR when you have time?
