### ISSUE TITLE
Update and review the following examples

### ISSUE THREAD

**Issue by helio-frota** [nodeshift-starters/opossum-examples#337]
- [x] angular
- [x] jquery
- [x] more-examples / multiple-express
- [x] more-examples / typescript-example
- [x] react
- [x] seneca

**Comment by pnaik1** [comment]
Updating dependencies in ember directory is throwing an error while starting the server

**Comment by helio-frota** [comment]
@pnaik1 thanks for the feedback!
Could you please create an issue for this with more information, for example the terminal logs output or screenshots ?
Then you can move forward on the next example while I take a look on the ember.

**Comment by helio-frota** [comment]
great work @pnaik1 :+1:

**Comment by pnaik1** [comment]
Thank you!
