### ISSUE TITLE
typescript-example is showing error 

### ISSUE THREAD

**Issue by pnaik1** [nodeshift-starters/opossum-examples#383]
The typescript-example is throwing error when starting the server
![Screenshot from 2022-08-17 15-55-48](https://user-images.githubusercontent.com/99238909/185098028-1f745d5c-b42c-4670-8e3b-cbe34f2852fb.png)
 
The problem is found in index.ts file(promise part) , the updation of typescript package has caused this error .. Its asking for the argument
![Screenshot from 2022-08-17 15-57-01](https://user-images.githubusercontent.com/99238909/185098661-cb1c68c8-ce36-439f-ac60-bc64119a8daf.png)
I tried to solve the issue by giving void return type to promise and it worked fine
![Screenshot from 2022-08-17 15-57-18](https://user-images.githubusercontent.com/99238909/185098923-ec401920-50a2-4da1-8347-18e6f8ab88d9.png)
![Screenshot from 2022-08-17 15-59-36](https://user-images.githubusercontent.com/99238909/185099449-e5557728-29b1-4e8c-ab7e-f6eaa68902bd.png)
Can you please take a look into it , whether its correct way or there is any alternative

**Comment by helio-frota** [comment]
@pnaik1 thanks for the pragmatic report!

I tested locally and yeah that is happening, probably some improvements on the TypeScript compiler that now shows that as error

```bash
❯ npm start

> typescript-example@1.0.0 start
> ts-node src/index.ts

/home/lm/code/opossum-examples/more-examples/typescript-example/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/index.ts:6:7 - error TS2794: Expected 1 arguments, but got 0. Did you forget to include 'void' in your type argument to 'Promise'?

6       resolve();
```


> I tried to solve the issue by giving void return type to promise and it worked fine

Can you please send the pull request with the fix ?
I'm going to assign this issue to you.
