### ISSUE TITLE
Need permission to create PR for adding more interesting and exciting examples

### ISSUE THREAD

**Issue by ArchitectAK** [nodeshift-starters/opossum-examples#419]
Hi There,

I need permission to push and create new branch and raise PR on this repo for adding more exciting examples.

I am current not having permission to create and push new branch to this repo, hence I am not able to raise PR.
![image](https://user-images.githubusercontent.com/3774909/210476461-357ca97f-0c60-40c6-be00-592b8f90ecdb.png)

**Comment by lholmquist** [comment]
you should be forking this repo to your user account and then creating a new branch and creating a PR with that.

See https://docs.github.com/en/get-started/quickstart/fork-a-repo#propose-changes-to-someone-elses-project
